[package]
name = "constrained-string-guesser"
version = "0.1.0"
edition = "2024"

[dependencies]
itertools = "0.14.0"
wordfreq = "0.2"

[dependencies.wordfreq-model]
version = "0.2"
features = ["large-en"]
